# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=128)),
                ('finish', models.IntegerField()),
                ('matchlength', models.DurationField()),
                ('matchdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Stable')),
            ],
        ),
        migrations.AddField(
            model_name='weeklystat',
            name='wrestler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Wrestler'),
        ),
    ]
