# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=128)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrestler', to='home.Wrestler')),
                ('wrestlers', models.ManyToManyField(blank=True, to='home.Wrestler')),
            ],
        ),
    ]
