# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-01 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180513_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='wrestlers',
        ),
        migrations.AddField(
            model_name='match',
            name='challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='home.Wrestler'),
        ),
        migrations.AddField(
            model_name='match',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='home.Wrestler'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='home.Wrestler'),
        ),
    ]
